services:
  postgres:
    profiles: ['edge', 'node']
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    ports:
      - '${DATABASE_PORT}:5432'
  pg_proxy:
    profiles: ['edge']
    image: ghcr.io/neondatabase/wsproxy:latest
    environment:
      APPEND_PORT: postgres:5432
      ALLOW_ADDR_REGEX: '.*'
      LOG_TRAFFIC: 'true'
    ports:
      - '${DATABASE_PROXY_PORT}:80'
    depends_on:
      - postgres
