packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@neondatabase/serverless': 0.9.4
  drizzle-orm: 0.29.4
  inngest: 3.35.1
  next: 15.1.6
  react: ^19.1.0
  react-dom: ^19.1.0
  zod: ^3.25.67
  # dev deps
  '@edge-runtime/vm': ^3.2.0
  '@next/eslint-plugin-next': ^15.1.6
  '@types/node': ^20
  '@types/react': ^19
  '@types/react-dom': ^19
  autoprefixer: ^10.4.20
  date-fns: 3.6.0
  dotenv: ^16.4.5
  drizzle-kit: ^0.20.6
  eslint: ^8
  inngest-cli: ^1.5.12
  msw: ^2.3.1
  tailwindcss: ^3.4.3
  postcss: ^8.4.47
  postgres: ^3.4.4
  testcontainers: ^10.24.2
  typescript: ^5.5.2
  vitest: ^3.1.2
