packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@neondatabase/serverless': 0.9.4
  drizzle-orm: 0.29.4
  inngest: 3.25.1
  next: 14.2.4
  react: ^18
  react-dom: ^18
  zod: ^3.23.8
  # dev deps
  '@edge-runtime/vm': ^3.2.0
  '@next/eslint-plugin-next': ^14.2.4
  '@types/node': ^20
  '@types/react': ^18
  '@types/react-dom': ^18
  autoprefixer: ^10.4.20
  date-fns: 3.6.0
  dotenv: ^16.4.5
  drizzle-kit: ^0.20.6
  eslint: ^8
  inngest-cli: ^1.1.0
  msw: ^2.3.1
  tailwindcss: ^3.4.3
  postcss: ^8.4.47
  postgres: ^3.4.4
  testcontainers: ^10.10.0
  typescript: ^5.5.2
  vitest: 1.6.0
