version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: 'postgres-${COMPOSE_PROJECT_NAME}'
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'
