version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: "postgres-${COMPOSE_PROJECT_NAME}"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: [5432]
