export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ width: '100vh', height: '100vh', margin: 0 }}>{children}</body>
    </html>
  );
}
