version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: 'postgres-${COMPOSE_PROJECT_NAME}'
    environment:
      POSTGRES_DB: ${DATABASE_DATABASE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
