export const users = {
  has_more: false,
  cursor:
    'AAAg-r7w8jUiFswI9nRrCdzcvKxZRo_BcE6T22LRSM9VEntdGy9IeV3pj8CnAXIz5iiefVwRk5zTXhwqsuIygAZiJOI7almSQ2DPjU25dW02IA',
  members: [
    {
      profile: {
        team_member_id: 'dbmid:AAChCxKa7-y8wlIeX5jcCkMNLtYxWRaefnM',
        account_id: 'dbid:AAAaAjkp_yekeB7wZ1AnqhrMGqfKJj-XRVg',
        email: 'admin-qa@elba.ninja',
        email_verified: true,
        secondary_emails: [],
        status: { '.tag': 'active' },
        name: {
          given_name: 'Admin',
          surname: 'Qa',
          familiar_name: 'Admin',
          display_name: 'Admin Qa',
          abbreviated_name: 'AQ',
        },
        membership_type: { '.tag': 'full' },
        joined_on: '2024-05-31T22:38:18Z',
        groups: ['g:27b266447023446d0000000000000003'],
        member_folder_id: '3679834209',
        root_folder_id: '5017744769',
      },
    },
    {
      profile: {
        team_member_id: 'dbmid:AABkgI9fKpLzJgblnvo48thSrLL4eZw8GuU',
        account_id: 'dbid:AADz72wUrCwBtzghz8NoJDx-sgabqGgq1Qs',
        email: 'app-registrations@elba.security',
        email_verified: true,
        secondary_emails: [],
        status: { '.tag': 'active' },
        name: {
          given_name: 'Elba',
          surname: 'QA',
          familiar_name: 'Elba',
          display_name: 'Elba QA',
          abbreviated_name: 'EQ',
        },
        membership_type: { '.tag': 'full' },
        joined_on: '2024-05-31T15:25:39Z',
        groups: ['g:27b266447023446d0000000000000003'],
        member_folder_id: '5014721249',
        root_folder_id: '5015820401',
      },
      roles: [
        {
          role_id: 'pid_dbtmr:AAAAAFMcx6E0tax39Kb0H671TzWLeE07dwaqFQ5fDRy2',
          name: 'Team',
          description: 'Manage everything and access all permissions',
        },
      ],
    },
    {
      profile: {
        team_member_id: 'dbmid:AACWjHGt35ukqy6nUfqPRvr9QmJJJBAGwmM',
        account_id: 'dbid:AAB3OjbEZyI28dAmCRlqnv6mRnuqTSZIPU0',
        email: 'developer.athithan@elba.ninja',
        email_verified: false,
        secondary_emails: [],
        status: { '.tag': 'invited' },
        name: {
          given_name: '',
          surname: '',
          familiar_name: '',
          display_name: '',
          abbreviated_name: '',
        },
        membership_type: { '.tag': 'full' },
        invited_on: '2024-05-31T20:42:37Z',
        groups: ['g:27b266447023446d0000000000000003'],
        member_folder_id: '5017085841',
        root_folder_id: '5017350241',
      },
    },
  ],
};
