version: '3.6'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_USER: slack
      POSTGRES_PASSWORD: slack
      POSTGRES_DB: slack
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '55432:5432'
  pg_proxy:
    image: ghcr.io/neondatabase/wsproxy:latest
    restart: always
    environment:
      APPEND_PORT: postgres:5432
      ALLOW_ADDR_REGEX: '.*'
      LOG_TRAFFIC: 'true'
    ports:
      - '5433:80'
    depends_on:
      - postgres
volumes:
  db_data:
