name: Quality checks

on:
  pull_request:
    branches: '*'
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  quality-checks:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      # Cache TurboRepo's artifacts and node_modules
      - name: Cache TurboRepo
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
            **/.turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint apps and packages
        run: pnpm lint

      - name: Run unit tests for apps and packages
        run: pnpm test
